######

name: AKS Cluster Provisioning with Terraform and Security

on:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  RESOURCE_GROUP: Kubernetes_GitOps

permissions:
  contents: read

jobs:
  provision-and-secure-cluster:
    name: Provision AKS and Apply Security
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    #- name: Setup Terraform
    #  uses: hashicorp/setup-terraform@v3
    #  with:
    #    terraform_version: 1.5.6

    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}


    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

   # - name: Terraform Init
    #  working-directory: terraform
   #  run: terraform init

   # - name: Terraform Apply (AKS Provision)
    #  working-directory: terraform
   #   run: terraform apply -auto-approve

        
